version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/air_quality_db
      - JWT_SECRET_KEY=jwt-secret-key-change-in-production
      - JWT_EXPIRATION_HOURS=12
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - FLASK_SECRET_KEY=dev-secret-key-change-in-production
      - FLASK_DEBUG=true
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    networks:
      - air-quality-network

  postgres:
    image: postgres:15
    container_name: air_quality_postgres
    environment:
      - POSTGRES_DB=air_quality_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - air-quality-network

volumes:
  postgres_data:

networks:
  air-quality-network:
    driver: bridge